### ISSUE TITLE
Show what is being entered

### ISSUE THREAD

**Issue by MHNightCat** [charmbracelet/vhs#468] opened 2024-04-18 06:11 UTC
**Is your feature request related to a problem? Please describe.**
When I want to demonstrate some more complex operations, I would like to have a display that can show the currently pressed keys for auxiliary instructions.

**Describe the solution you'd like**
Displays which keys are currently being pressed at the bottom or in a customizable location.

**Additional context**
[Example](https://github.com/charmbracelet/vhs/assets/107802416/6c01fad3-f0aa-4ddf-866b-04fd79f3b729)

**Comment by Utagai** [comment] 2024-05-13 03:17
This is something I've wanted pretty badly for another project of mine where the keypresses are important to show in the recording. I've made some headway over [here](https://github.com/utagai/steno).

P.S. After talking about it with someone on the Charm Discord, I decided that it should be done in a third program, rather than inside `ttyd` or `vhs`.

**Comment by Utagai** [comment] 2024-05-13 04:28
Well, that was quick! Sorry for the extra ping to anyone subscribed to this issue. I got the green light for attempting to put this into `vhs`, so I'll be hacking on moving my linked repo into `vhs` for now.

@maaslalani I'm thinking we either close this issue or #164, since I'm pretty sure they are duplicates.

**Comment by maaslalani** [comment] 2024-05-13 04:43
Closing as duplicate of #164

**Closed** 2024-05-13 04:43 UTC
Labels: enhancement
