### ISSUE TITLE
expected vs actual output

### ISSUE THREAD

**Issue by apettel** [charmbracelet/vhs#288] opened 2023-04-15 16:07 UTC
expected:

<img width="1005" alt="expected" src="https://user-images.githubusercontent.com/62218880/232236149-dd967d11-8c50-4002-87b1-41caddf60897.png">

actual:

![actual](https://user-images.githubusercontent.com/62218880/232236287-e0599a85-7249-4a60-b89d-4a2caa384134.gif)

**Comment by maaslalani** [comment] 2023-04-17 17:05
Hey, thanks for reporting this bug! It's a duplicate of https://github.com/charmbracelet/vhs/issues/249

This will be fixed when the next `xterm.js` version is released:
https://github.com/xtermjs/xterm.js/issues/4120

**Closed** 2023-04-17 22:55 UTC
