### ISSUE TITLE
Inconsistent playback speed

### ISSUE THREAD

**Issue by bakks** [charmbracelet/vhs#367] opened 2023-08-22 22:13 UTC
**Describe the bug**
I'm generating gifs with tape files and using the `Sleep` command to stop and wait afterwards, i.e. I have blocks of time where I just want the cursor to blink. The issue is that the gif doesn't stay in this state for the requested amount of time and in fact the cursor doesn't blink with a regular cadence. It seems like maybe frames are being dropped, either during recording or when it's converted to a gif. See example:

![intro](https://github.com/charmbracelet/vhs/assets/1172710/516a32cd-c2ff-43d7-9f19-ddcfda935b58)

I don't see this issue in the example gifs and so I suspect that something is a little broken with my setup, maybe I'm using an older version of some library. Any advice is appreciated!

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: MacOS 12.6.8 on an amd64
 - Shell: zsh, same behavior in bash
 - Terminal Emulator: kitty, same with Terminal.app
 - ffmpeg 6.0

**To Reproduce**

Here is the output when I run vhs, which shows the commands being executed:

```
Generating gif/intro.gif
vhs intro.tape
File: intro.tape
Host your GIF on vhs.charm.sh: vhs publish <file>.gif
Output .gif gif/intro.gif
Source common.tape
common: Require butterfish
common: Set FontSize 28
common: Set Padding 14
common: Set Theme Monokai Pro
common: Hide
common: Type cd ~/butterfish
common: Enter 1
common: Type clear
common: Enter 1
common: Sleep 2s
common: Show
Type head -n 100 README.md | butterfish prompt 'This is a readme for a unix command, succinctly explain what the command does'
Sleep 1s
Enter 1
Sleep 45s
Creating gif/intro.gif...
```

**Comment by bashbunni** [comment] 2023-08-24 14:58
To confirm, have you changed the playback speed, frame rate, or typing speed of the recorded GIF? Also, are you using the latest release of VHS?

**Comment by caarlos0** [comment] 2023-08-24 18:22
the times that kind of thing happened to me was because the resolution of the gif was too high, and the recording was basically dropping frames.

maybe its a similar issue? not sure what else causes frames to be drop though

**Comment by maaslalani** [comment] 2023-08-24 18:27
Yes, I believe this occurs when there are LOTs of frames to process. Somewhere along the lines we are either not recording the correct number of frames or or dropping frames.

One solution that may slow down the recording in this case is to set the framerate number to a lower number as it is probably not recording at 50-60 frames but is rendering as if it did:

```elixir
Set Framerate 25
```

Also if that doesn't work, I'd recommend disabling the `CursorBlink` so the cursor isn't distracting.

```elixir
Set CursorBlink false
```

**Comment by bakks** [comment] 2023-08-24 19:55
Thanks for those suggestions, all!

> To confirm, have you changed the playback speed, frame rate, or typing speed of the recorded GIF?

Previously I experimented with playback speed and typing speed but saw the same issue

> Also, are you using the latest release of VHS?

Confirmed I'm using vhs v0.6.0 which I believe is the latest

> One solution that may slow down the recording in this case is to set the framerate number to a lower number as it is probably not recording at 50-60 frames but is rendering as if it did

This helped a bunch! See gif below, I think you're correct that reducing overall frames seems to help.

> Also if that doesn't work, I'd recommend disabling the CursorBlink so the cursor isn't distracting.

This is a good suggestion but for some reason it's not working for me -- i.e. I tried `Set CursorBlink false` in my tape file and it is still blinking, I'm not sure why.

Anyway dropping the framerate smooths the gif out enough for my purposes, thanks for your help. This is at a framerate of 20:


![intro](https://github.com/charmbracelet/vhs/assets/1172710/0c6de426-15d4-441d-a089-6a7bc2b0c344)

**Comment by maaslalani** [comment] 2023-08-24 20:03
> > Also if that doesn't work, I'd recommend disabling the CursorBlink so the cursor isn't distracting.
> 
> 
> 
> This is a good suggestion but for some reason it's not working for me -- i.e. I tried `Set CursorBlink false` in my tape file and it is still blinking, I'm not sure why.
> 

This might be because you'll need the latest VHS `@main` as opposed to the latest release since I believe this feature is brand new.

**Comment by maaslalani** [comment] 2023-08-24 20:03
Hmmmm... sorry never mind I believe it was introduced in 0.6.0

https://github.com/charmbracelet/vhs/releases/tag/v0.6.0

**Comment by bakks** [comment] 2023-08-24 20:26
@maaslalani I think there's something goofy going on with the `Source` command, here's my attempt to isolate the problem.

test.tape
```
Output test.gif

Source common2.tape

Set Theme "Monokai Pro"
Set CursorBlink false

Type "echo 'Hello World'"
Enter
Sleep 5s
```

common2.tape
```
Set FontSize 28
Set Padding 14
Set CursorBlink false
```

If I set those two files up and then run `vhs test.tape` I obverve the following behavior:
- If I don't do the `Source` command and instead put everything in the same file it all works
- If I do `Set` before the `Source` command it seems to work
- It seems like the `Set` calls after `Source` are interpreted as comments, they don't seem to work and they're printed in grey in the terminal
- But it also seems like `Set CursorBlink false` in `common2.tape` doesn't quite work either.

So there seems to be a bug related to `Source` and possibly `Set CursorBlink` specifically.

**Comment by robinovitch61** [comment] 2024-01-01 20:50
Possibly related to #88

**Comment by mikelorant** [comment] 2024-03-11 00:52
@maaslalani Can we mark this as a duplicate #88 and close this.

**Comment by bashbunni** [comment] 2024-03-12 23:26
Hey there, this is in fact a duplicate of #88. I'm going to close this to keep all of the discussion in one place! Thank you for raising the issue, this is definitely something worth figuring out.

**Closed by bashbunni** 2024-03-12 23:26 UTC
Labels: bug, duplicate
